services:
  - type: web
    name: waschplan-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_PATH
        value: /var/data/washraum.sqlite
      - key: SESSION_SECRET
        generateValue: true
      - key: PUBLIC_APP_URL
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_SECURE
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_FROM
        sync: false
    disk:
      name: washraum-data
      mountPath: /var/data
      sizeGB: 1
